apiVersion: v1
kind: Service
metadata: 
  name: redis-cluster-ip-service
spec:
  selector:
    component: redis
  type: NodePort
  ports:
  - name: "http"
    protocol: TCP
    port: 6379
    targetPort: 6379
    nodePort: 30080
  - name: "https"
    protocol: TCP
    port: 6379
    targetPort: 6379
    nodePort: 30080  
